### ISSUE TITLE
La conception de la BDD et UML ne sont pas compatibles 

### ISSUE THREAD

**Issue by backhandx** [Naoufal-ELALLOUCH/projetGenieLogiciel#1]
Par exemple, les attributs d'un atelier ne figurent pas dans la classe Atelier, ce qui va alourdir le code de la servlet qui s'occupe de la gestion d'atelier. Je ne vois pas l'intérêt du package BBD.

**Comment by Naoufal-ELALLOUCH** [comment]
Je suis du même avis puisque déjà la classe atelier par exemple lui manque plusieurs attributs comme thème. ...
Et je pense que ça ne sert à rien de  répéter les mêmes choses au niveau des packages bdd et modèles.

Dites nous ce que vous en pensez.

**Comment by charllie** [comment]
certains attributs ne figurent pas sur l'UML mais doivent y figurer oui (faute de temps)
l'intérêt du package bdd c'est de pouvoir clarifier et séparer les actions sur la base de données
par ex BddUtilisateur aura une méthode enregistrer qui permettra de mettre à jour l'utilisateur à partir de l'objet Utilisateur
